# create copy from this file with "config.py" name
# in this directory

CLUSTERS_NUM = 10
BUDGET = 10
DEFAULT_NUM_AGENT = 5

THRESHOLDS_NUM = 10
DISCOUNT_FACTOR = 0.99

AC_EPISODES = 3e3

DEFAULT_STATE_VALUE = 0.0

UTILITY_INTERVAL_NUM=10